// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZBBET_kKGSiQ0uKz7FfdJ_W9jTcWV_KE',
    appId: '1:391234975580:web:1ca0ec61750ad551737399',
    messagingSenderId: '391234975580',
    projectId: 'playmyhitdev',
    authDomain: 'playmyhitdev.firebaseapp.com',
    storageBucket: 'playmyhitdev.appspot.com',
    measurementId: 'G-65S9CCY6FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjuIxgWLxe-XEubTrUZ2ONawkRz_hw3tQ',
    appId: '1:391234975580:android:a5d3fec3b5768a35737399',
    messagingSenderId: '391234975580',
    projectId: 'playmyhitdev',
    storageBucket: 'playmyhitdev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2ErMrlWIXoRsLouUM9bEz1PzLXMjZVZw',
    appId: '1:391234975580:ios:26d7d8b0f1fe20c1737399',
    messagingSenderId: '391234975580',
    projectId: 'playmyhitdev',
    storageBucket: 'playmyhitdev.appspot.com',
    iosClientId: '391234975580-i5da9tmjgk5rjo11d9jrno0522utngkj.apps.googleusercontent.com',
    iosBundleId: 'com.example.playmyhit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2ErMrlWIXoRsLouUM9bEz1PzLXMjZVZw',
    appId: '1:391234975580:ios:d59fb91bd054b331737399',
    messagingSenderId: '391234975580',
    projectId: 'playmyhitdev',
    storageBucket: 'playmyhitdev.appspot.com',
    iosClientId: '391234975580-vdhke0ar05em4duarvvc7916i7ggo8hr.apps.googleusercontent.com',
    iosBundleId: 'com.example.playmyhit.RunnerTests',
  );
}
